"""Export trained value-network weights for embedding in main.py.

After training, run this script to produce:
1. A .npz file with the numpy weights
2. A base64-encoded string that can be pasted directly into main.py
"""

import base64
import io
import os
import sys
import numpy as np

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from strategy.actor_net import load_weights


def export_base64(npz_path):
    """Read a .npz weights file and return a base64-encoded string."""
    with open(npz_path, "rb") as f:
        data = f.read()
    return base64.b64encode(data).decode("ascii")


def generate_inline_weights(npz_path, output_py_path=None):
    """Generate a Python snippet with the weights embedded as base64.

    If output_py_path is given, writes the snippet to that file.
    Otherwise prints to stdout.
    """
    b64 = export_base64(npz_path)

    snippet = f'''# Auto-generated by strategy/export_weights.py
# Value network weights ({len(b64)} chars base64)
import base64, io, numpy as np

_WEIGHTS_B64 = "{b64}"

def _load_inline_weights():
    data = base64.b64decode(_WEIGHTS_B64)
    buf = io.BytesIO(data)
    npz = np.load(buf)
    layers = []
    i = 0
    while f"W_{{i}}" in npz:
        W = npz[f"W_{{i}}"]
        b = npz[f"b_{{i}}"]
        has_relu = bool(npz[f"relu_{{i}}"][0])
        layers.append((W, b, has_relu))
        i += 1
    return layers
'''

    if output_py_path:
        with open(output_py_path, "w") as f:
            f.write(snippet)
        print(f"Written inline weights to {output_py_path}")
    else:
        print(snippet)

    return snippet


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Export value-net weights")
    parser.add_argument("npz_path", help="Path to the .npz weights file")
    parser.add_argument("--output", "-o", help="Output .py file (default: stdout)")
    args = parser.parse_args()

    generate_inline_weights(args.npz_path, args.output)
